name: tv_display
description: Vertical TV ad display

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  http: ^0.12.2
  wakelock: ^0.2.1
  xml2json: ^4.4.0
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
    - assets/